apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-python-session-1
spec:
    replicas: 3
    selector:
        matchLabels:
            app: tf-python-session-1
    template:
        metadata:
            labels:
                app: tf-python-session-1
        spec:
            containers:
            - name: tf-python-session-1
              image: christophergarrick/tf-python-session-1:latest
              ports:
                - containerPort: 8080
              env:
                - name: PORT
                  value: "8080"
                - name: ENV_MESSAGE
                  valueFrom:
                    configMapKeyRef:
                      name: tf-python-cm
                      key: ENV_MESSAGE

---
apiVersion: v1
kind: Service
metadata:
  name: tf-python-session-1
spec:
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 8080
          protocol: TCP
    selector:
        app: tf-python-session-1
